### ISSUE TITLE
Realtime Performance

### ISSUE THREAD

**Issue by cretz** [esimov/pigo#15]
A quick view of an example I found this happening per frame:

https://github.com/esimov/pigo/blob/747334f8411a7ef22aa7e67cfa63d17c486b9cce/examples/web/main.go#L131-L137

Why create the object and rerun that same unpack logic every time on the same source bytes. Should there be a `Clone` on the `Pigo` struct that just copies everything to a new struct to be better performing when running over and over?

**Comment by esimov** [comment]
I realized that mistake when I transferred the same code section on the Python implementation, but didn't took the effort the fix it on the web example. So this is fixed by now, however I don't see this change to produce a major speedup, maybe a marginally one, but for the memory footprint definitely it's much better.

It doesn't even need to clone the Pigo struct, it's enough to move it above the for loop, and parse the cascade file only once.

**Comment by cretz** [comment]
Nice, thanks.
