### ISSUE TITLE
Mouth detection / facial landmarks on WASM demo

### ISSUE THREAD

**Issue by montanaflynn** [esimov/pigo#24]
Hello, I got the WASM demo working and it's great. Is there a plan / easy way to enable all facial landmarks? I see some code is commented out. Thanks!

**Comment by esimov** [comment]
The implementation is missing for facial landmark points detection for a simple reason: the download of the binary files are taking too much time for the first load (since they are many). The code for the binary download and parser has been integrated but commented out as you have remarked. The only thing missing is the integration of the facial points detection. The integration would be straightforward, but the problem as I mentioned is not with the integration itself but the time needed for the first download. That's the reason why it's missing.

**Comment by esimov** [comment]
@montanaflynn I have extended the Webassembly demo with facial landmark points detection too. Please check the [Readme](https://github.com/esimov/pigo/blob/master/wasm/README.md) file for the instructions if needed. Also you might reduce the canvas size to 640x480 for better performance. Currently the resolution is set to a pretty high level.
