### ISSUE TITLE
Passing output value via a variable (Python)

### ISSUE THREAD

**Issue by rgvxlens** [esimov/pigo#36]
Hi there! I'm trying to pass the values for the eyes separately using the blinkdet example, but seems like it outputs the values for both the eyes together and not separately (just outputting max_radius)

Is there a way to output the values that I get using -json via a particular variable or just output the values (max_radius) of both the eyes separately?

**Comment by esimov** [comment]
Not sure if I understand correctly what you are trying to achieve? Can you detail a little bit?

**Comment by rgvxlens** [comment]
So the values that I get if I just use the command line version of Pigo with -json argument are:
`[{"face":{"x":242,"y":363,"size":256},"eyes":[{"x":230,"y":316,"size":21},{"x":233,"y":413,"size":21}]}]`

I'm trying to get similar output using the Python program for the "blinkdet" example. In there, I've identified _max_radius = int(det[2]*0.45)_ where max_radius is the variable for storing the iris radius for both of the eyes (I guess?).

Is there a way to output the max_radius for the left separately and the right eye separately?

**Comment by esimov** [comment]
The only way on that example to identify the left and right eye separately is to introduce an index and check inside the `if show_pupil:` statement from line 86 if it's odd or even. The left eye is detected first. Otherwise the Go code needs to be extended. I was forced to use an 1D array, since it was not possible to transfer a multi dimensional array trough array pointer from Go to Python via a shared object. That was the reason of using in python some sort of trickery in identifying the detected objects.

https://github.com/esimov/pigo/blob/master/examples/blinkdet/blinkdet.py#L86

**Comment by rgvxlens** [comment]
I tried implementing the same but have not been successful. Could you explain a bit more, or give me a code-based example?

**Comment by esimov** [comment]
Not sure if I understand what you are trying to achieve? The code-based example is that one I have provided above.
